# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseML' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseML

  # Core de Firebase
  pod 'Firebase/Core'
  
  # Manejo de Vision y Machine Learning
  pod 'Firebase/MLVision'

  # Manejo del modelo que detecta letreros en Video
  pod 'Firebase/MLVisionLabelModel'

  # Para la detección del código de barras
  pod 'Firebase/MLVisionBarcodeModel'


end
